development:
  adapter: mysql
  database: funda_development
  username: root
  password: Qwerty2007.
  encoding: utf8
 
test:
  adapter: mysql
  database: funda_test
  username: root
  password: Qwerty2007.
  encoding: utf8

production:
  adapter: mysql
  database: funda_production
  username: root
  password: Qwerty2007.
  encoding: utf8